"""fix table

Revision ID: d28df7abfc3e
Revises: 3824370b7720
Create Date: 2024-08-07 10:28:22.728585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28df7abfc3e'
down_revision = '3824370b7720'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('body', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'body')
    # ### end Alembic commands ###
